version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - buschtoens
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.24.0
    - 7.25.0
    - 7.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.4.0
    - 5.6.3
    - 5.7.0
  - dependency-name: ember-template-lint
    versions:
    - 2.18.1
    - 3.0.0
    - 3.0.1
  - dependency-name: "@clark/eslint-config-ember-typescript"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
  - dependency-name: ember-cli
    versions:
    - 3.25.3
